version: '3'
services:
  app:
    build: .
    depends_on:
      - mysqld
    volumes:
      - .:/app
    environment:
      DSN: admin:admin@(mysqld)/api-server?parseTime=true
    tty: true

  mysqld:
    image: mysql:5.7
    platform: linux/amd64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: api-server
      TZ: Asia/Tokyo
